spring:
  application:
    name: Library-Management-System

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/LMS_DB?useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

twilio:
  account-sid:  ${TWILIO_ACCOUNT_SID:}
  auth-token:   ${TWILIO_AUTH_TOKEN:}
  from-whatsapp: ${TWILIO_PHONE_NUMBER:}


sendgrid:
  api-key: ${API_KEY:}
  from-email: ${FROM_EMAIL:}

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  packages-to-scan: com.example.LMS.controller
  exclude-filters:
      name: com.example.LMS.controller.advice.GlobalExceptionHandler
      type: ASSIGNABLE_TYPE

